spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/featureflagdb
    username: featureflag_user
    password: featureflag_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jwt:
    secret: ClaveSeguraParaFeatureFlag7_API_HS512_ClaveSeguraParaFeatureFlag7_API
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: false
  flyway:
    url: jdbc:postgresql://localhost:5432/featureflagdb
    user: featureflag_user
    password: featureflag_pass
    baseline-on-migrate: true
    connect-retries: 5